spring.application.name=phishing-detection-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/phishing_detection
spring.datasource.username=postgres
spring.datasource.password=uday

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect